baseURL = "/"
languageCode = "en-us"
title = "PEP Class 2020"
theme = "hugo-ink"
paginate = 5
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

copyright = "Â© PEP 2020"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
	subtitle = "Ocean and Environmental Sciences"

	# Optional 64x64 avatar image.
	avatar = "/images/dac-logo-white278x80.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "light" # "dark" or "auto"
	customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "About"
url = "/intro"
weight = 1

[[menu.main]]
name = "Classes"
url = "/class"
weight = 2

[[menu.main]]
name = "R Resources"
url = "/r_resources"
weight = 6

[[menu.main]]
name = "Syllabus"
url = "/docs/PEP2020_syllabus.pdf"
weight = 4

[[menu.main]]
name = "Schedule"
url = "/Schedule"
weight = 3

#[[params.social]]
#name = "Github"
#icon = "github"
#url = "https://github.com/knadh/hugo-ink"

#[[params.social]]
#name = "RSS"
#icon = "rss"
#url = "/index.xml"

[taxonomies]
   tag = "tags"
   category = "categories"
